### ISSUE TITLE
body too big error

### ISSUE THREAD

**Issue by starjun** [agentzh/lua-resty-multipart-parser#1]
function _M.new(body, content_type)  
-- can first check body is nil then read form  ngx.req.get_body_file() 
        if not body then 
            local datafile = ngx.req.get_body_file()
            if datafile then
                local fh, err = io.open(datafile, "r")
                if fh then
                    fh:seek("set")
                    body = fh:read("*a")
                    fh:close()
                end
            end
        end

**Comment by agentzh** [comment]
@starjun What are you suggesting here? The API of this library just accepts a Lua string as the argument. It's the caller's responsibility to prepare the request body in a Lua string anyway.

**Comment by starjun** [comment]
Got it，3Q,
