### ISSUE TITLE
pcre error

### ISSUE THREAD

**Issue by hy05190134** [agentzh/lua-resty-multipart-parser#2]
header =

 "multipart/form-data; boundary=X3xzCbpcHmO20eREKeawv1em7LqqtVd1ebPldf; charset=UTF-8"

match_table[1] = nil                                                                                                                           
match_table[2] = nil                                                                                                                           
local m, err = re_match(header,                                                                                                                
               [[;\s*boundary\s*=\s*(?:"([^"]+)"|([-|+*$&!.%'`~^\#\w]+))]],                                                                    
                       "joi", nil, match_table)                                                                                            
 if m then                                                                                                                                      
      return m[1] or m[2]. ---  **m[1] is nil, m[2] is nil** 
 end

-------------------

header = ""

match_table[1] = nil                                                                                                                           
match_table[2] = nil                                                                                                                           
local m, err = re_match(header,                                                                                                                
               [[;\s*boundary\s*=\s*(?:"([^"]+)"|([-|+*$&!.%'`~^\#\w]+))]],                                                                    
                       "joi")                                                                                            
 if m then                                                                                                                                      
      return m[1] or m[2]. ---  **m[1] is false, m[2] is X3xzCbpcHmO20eREKeawv1em7LqqtVd1ebPldf** 
 end

maybe it is bug, but I don't know why cause this?

@agentzh

**Comment by hy05190134** [comment]
@agentzh  why set match_table[1] and match_table[2] nil, 感觉不起作用呀，table 还是空的

**Comment by hy05190134** [comment]
另外，想问下，嵌套下的 m[1] 是表示最外层的匹配，m[2] 是里面的 括号的匹配吗？

**Comment by agentzh** [comment]
@hy05190134 No Chinese is allowed here. If you really want to use Chinese, please join and post to the openresty (Chinese) mailing list instead. Thanks for your cooperation. Besides, I cannot understand your description at all.

**Comment by hy05190134** [comment]
I just mean why the result is different when we use the fourth and fifth params in ngx.re.match function, I have already show the result. @agentzh
